#
# This file contains the minimal configuration required for Synapse to run.
# For a list of all available configuration options, along with documentation for each option, see:
# https://github.com/Automattic/matrix-env/blob/522227eeb7b98647a962ba027046016cf1f8b726/data/homeserver.yaml
#

server_name: "matrix.test"
public_baseurl: "http://localhost:8008"

trusted_key_servers:
  - server_name: "matrix.org"

report_stats: false
log_config: "/synapse/config/log.config"
signing_key_path: "/synapse/config/signing.key"

pid_file: "/synapse/data/homeserver.pid"
media_store_path: "/synapse/data/media_store"

registration_shared_secret: "YTV.UDYmbtn5TTh8;1l#lNo8sXx2n8qQBE^~g1GZEioyvJd1n0"

listeners:
  - port: 8008
    tls: false
    type: http
    x_forwarded: true

    resources:
      - names: [client, federation]
        compress: false

database:
  name: psycopg2
  args:
    user: synapse
    password: synapse
    database: synapse
    host: matrix-env-synapse-database
    port: 5432
    cp_min: 5
    cp_max: 10
